services:
  - type: web
    name: fittrack-backend
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/fittrack-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JWT_SECRET
        generateValue: true
      - key: SUPABASE_URL
        value: https://qindoeldnsrybeixezhs.supabase.co
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpbmRvZWxkbnNyeWJlaXhlemhzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MzgzNTkzNCwiZXhwIjoyMDY5NDExOTM0fQ.fp69aqLIE8UgYIwjh9MmFC9EcFBY917UXvH1k1GlAko
      - key: ALLOWED_ORIGINS
        value: https://your-frontend-domain.com